### ISSUE TITLE
add extra domains to app.swiftype.com indexing

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/sphinx_ansible_theme#10]
In order to make the search functionality work across sites hosting Ansible documentation we need to few extra domains to be added to https://app.swiftype.com :

* https://sphinx-ansible-theme.readthedocs.io <-- ready (try search on it)
* https://molecule.readthedocs.io - wip
* https://ansible-lint.readthedocs.io - wip

At this moment the search returns only results from `docs.ansible.com` rendering in-site search useless.

We are unlikely to want to limit the search to a single project. Also the fact that swifttype does not have a free plan forces us to seek a single search engine implementation.

**Comment by webknjaz** [comment]
This is not going to work for now.
