### ISSUE TITLE
Wrong license?

### ISSUE THREAD

**Issue by webknjaz** [ansible-community/sphinx_ansible_theme#26]
When extracting the theme, @ssbarnea dropped in MIT license into the project metadata.
[This](https://opensource.stackexchange.com/a/6063/11301) suggests that the derivative work should be GPLv3-compatible (since it [comes from ansible/ansible](https://github.com/ansible/ansible/tree/devel/docs/docsite/_themes/sphinx_rtd_theme) where the [majority of the repo content is GPLv3](https://github.com/ansible/ansible/blob/devel/COPYING)).

@abadger @acozine @gundalow does this sound right?

**Comment by ssbarnea** [comment]
That is a good question.  At source I used https://github.com/readthedocs/sphinx_rtd_theme/blob/master/LICENSE -- as that is the original RTD theme. Now, if Ansible team wants to relicense its "extensive" customizations as GPL, that is allowed by MIT.

Shortly, I do not care which license the theme is as long we can all use it. It can be any of them and I do not have anything against changing it, if needed.

The only remark would be that a GPL license could be a problem if a project wants to ship its documentation somehow. Now only two projects are using this theme, and none of them is shipping any docs, only publishing it, which is something different.

**Comment by samccann** [comment]
Alas, I know little about licensing requirements/recommendations.

**Comment by webknjaz** [comment]
> Now only two projects are using this theme

In fact, I've also added it to ansible-pylibssh but it's almost empty atm.

**Comment by webknjaz** [comment]
> if Ansible team wants to relicense its "extensive" customizations as GPL, that is allowed by MIT.

It's not just about what the team "wants". We should play by the rules. The contents of ansible/ansible repo are GPLv3 and copying things from there demands that copy to comply with GPLv3 requirements.

Relicensing is a different thing. When multiple authors contribute code, they do that under the license that was in place at the time of the contribution. Changing the license usually requires each of the substantial contributions to explicitly agree with it. So the right process is to ask each and every contributor for the approval.

**Comment by webknjaz** [comment]
This repo doesn't have the original RTD theme vendored anymore. So most of the things come from ansible/ansible or me/Sorin. I suppose since most (all) of the derived stuff was written by @acozine — it should be enough to have @acozine's explicit permission to relicense this project to MIT or BSD.

Note: ansible/ansible uses BSD for module utils so that people can link against it w/o having to follow the requirements of GPL.

**Comment by ssbarnea** [comment]
@webknjaz Make a PR to switch license and add at least @acozine as reviewer. I will be happy to support such a move. We want to make this theme as easy to reuse by anyone, regardless how they license their code or docs.
