### ISSUE TITLE
make docs.ansible.com specific parts configurable

### ISSUE THREAD

**Issue by evgeni** [ansible-community/sphinx_ansible_theme#27]
the theme currently has the following parts that are (IMHO) specific to docs.ansible.com:
* the globalnav in ansible_extrabody.html (ansiblefest etc)
* JS for trackers from Google and Red Hat

if the theme is supposed to be usable outside of the docs.ansible.com site, it'd be cool if users could disable these.

**Comment by webknjaz** [comment]
Implemented.
