### ISSUE TITLE
GitHub releases?

### ISSUE THREAD

**Issue by felixfontein** [ansible-community/sphinx_ansible_theme#35]
Right now, GitHub says the latest release is 0.3.2 (from July 2020), while the latest actual release is 0.7.0 (from yesterday). I think it would be helpful if GitHub releases would be created for the release tags. This also makes it possible to subscribe to releases from this repository and actually be informed when there's a release :)

**Comment by webknjaz** [comment]
Yep, that crossed my mind when I was working on the automation for pygments. I also wanted to auto-create release discussions (there's now a checkbox for that). But I'm not sure when I'll be able to invest more time into this.

**Comment by bmillemathias** [comment]
there was a release few weeks ago, can this issue be closed ?

**Comment by felixfontein** [comment]
It definitely can :)
