### ISSUE TITLE
Add Expand/collapse capability

### ISSUE THREAD

**Issue by samccann** [ansible-community/sphinx_ansible_theme#39]
Based on the [Documentation working group meeting,](https://github.com/ansible/community/issues/579#issuecomment-896271973) we would like to investigate the option to add expand/collapse capability to the Ansible theme.

This is still an idea we need to flesh out some more, but the hope is that we can start creating Ansible example pages where we have multiple components to each example. At the minimum, a playbook and the associated output. Then the user could click on the title of an example that sounds interesting and 'expand' to see the example. This would make it potentially easier when scrolling through large example pages to find what's of interests without having to scroll past long coding or output sections that aren't of interest.

If this is possible, we could then expand the functionality to the module docs pages as well.

**Comment by webknjaz** [comment]
We need to see if this really belongs in the theme, though. It may be the case that the end-users could just use third-party extensions to achieve this.

Quick googling revealed https://sphinx-togglebutton.rtfd.io and https://sphinx-toolbox.rtfd.io/en/stable/extensions/collapse.html.

Also, somebody on the Write The Docs slack recently mentioned the new hotness — https://sphinx-design.readthedocs.io/en/furo-theme/dropdowns.html.

**Comment by webknjaz** [comment]
@samccann should we close this in the light of https://github.com/ansible-community/antsibull/pull/303#issuecomment-918449294?

**Comment by samccann** [comment]
agreed and thanks!
