### ISSUE TITLE
Tracking an "ng" theme

### ISSUE THREAD

**Issue by webknjaz** [ansible-community/sphinx_ansible_theme#41]
I have a plan to make a new theme based on Furo or its siblings. It'll be responsive, accessible, and support dark mode. It's currently impossible to just inherit Furo but there's a lot of improvements happening in the Sphinx ecosystem that will have a great impact on our ability to make modern themes.
One of the developments is tracked here https://github.com/python/docs-community/issues/1#issuecomment-974897934.
P.S. This will probably need to happen in a new repo but until then, I'll keep the issue here.

**Comment by samccann** [comment]
Any new theme should have top accessibility features (Yah, I know that's vague at the moment). It should also be a responsive design (aka work reasonably well on iphones as well as laptops so to speak).

**Comment by webknjaz** [comment]
> Any new theme should have top accessibility features (Yah, I know that's vague at the moment). It should also be a responsive design (aka work reasonably well on iphones as well as laptops so to speak).

That's what Furo implements. I wonder if we could use it and color differently or smth along the lines.

**Comment by webknjaz** [comment]
> Additionally the purpose of the new theme is to address several issues in this repository that affect community projects and tooling.

So the open issues?

> Plus allow support for newer versions of Sphinx to avoid compatibility problems with requirements.

The current test matrix includes a variety of Sphinx versions already FWIW.

**Comment by ssbarnea** [comment]
@webknjaz As I already moved all devtools projects to mkdocs, I will no longer be able to maintain the theme (sadly I still have to create a custom ansible theme based on mkdocs material).

If anyone else needs extra permissions on this repo, ping me or @webknjaz

**Comment by webknjaz** [comment]
No need to close this issue, it's my personal effort.
@ssbarnea you may need to transfer the owner on PyPI to me of you don't want to be a bus factor, I suppose.

**Comment by ssbarnea** [comment]
I made you owner too pypi, @gundalow was already, good to have few backups if needed.

**Comment by webknjaz** [comment]
@ssbarnea and TestPyPI?
