### ISSUE TITLE
Lynx does not like <select> outside <form>

### ISSUE THREAD

**Issue by felixfontein** [ansible-community/sphinx_ansible_theme#47]
When browsing with lynx to https://sphinx-ansible-theme.readthedocs.io/en/latest/, it complains about "Broken HTML". This turns out to be Lynx expecting `<select>` to be inside a `<form>`, which I do think is **not** required by HTML 5 (https://html.spec.whatwg.org/multipage/form-elements.html#the-select-element, https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#form-owner, https://html.spec.whatwg.org/multipage/forms.html#form-associated-element).

Making Lynx happy isn't too hard, we'd basically need a dummy `<form>` around the select element.

(Ref: https://github.com/ansible/ansible/pull/76759#issuecomment-1027629506)

**Comment by samccann** [comment]
I'm in favor of making lynx happy as it is a tool we know our readers use (along with screen readers). Adding this to the Ansible Diversity WG project to keep track.
