### ISSUE TITLE
incompatible with newer sphinx_rtd_theme 1.0.0

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/sphinx_ansible_theme#50]
I discovered that our theme breaks with `sphinx_rtd_theme==1.0.0` and I had to [pin it down](https://github.com/ansible-community/ansible-lint/pull/1852) until I discover what caused that.

We currently have no version bounds on this package, so we should add one.

**Comment by felixfontein** [comment]
I don't think it is a general incompatibility, since https://sphinx-ansible-theme.readthedocs.io/en/latest/ looks good (built from the latest commit).
