### ISSUE TITLE
Top left logo url is 404 instead of index on GH pages

### ISSUE THREAD

**Issue by oraNod** [ansible-community/sphinx_ansible_theme#72]
Click the top-left logo and get a 404: https://ansible-collections.github.io/community.dns/branch/main/ 

Click the top-left logo and it points to the index: https://ansible-sdk.readthedocs.io/en/latest/

**Comment by felixfontein** [comment]
The link's URL is currently hardcoded to `/`: https://github.com/ansible-community/sphinx_ansible_theme/blob/main/src/sphinx_ansible_theme/extrabody.html#L20

**Comment by felixfontein** [comment]
#75 with some support on antsibull-docs' side and some support on github-docs-build's side will fix this.

**Comment by felixfontein** [comment]
The antsibull-docs side is implemented in https://github.com/ansible-community/antsibull-docs/pull/77.
