### ISSUE TITLE
Make :envvar: output more obvious that it's a hotlink

### ISSUE THREAD

**Issue by samccann** [ansible-community/sphinx_ansible_theme#73]
Today I learned - if we use :envvar: for environment variables, they are hotlinked on docs.ansible.com. See https://docs.ansible.com/ansible/latest/reference_appendices/config.html#action-warnings for an example.

The output unfortunately doesn't give the reader a hint that this is a hotlink. Maybe if we changed the text to blue it might help?

**Comment by samccann** [comment]
![image](https://user-images.githubusercontent.com/30267855/204590790-b4ba179c-ffa0-4c96-8820-f921c8b74172.png)

That image shows the envvar, but it's not obvious unless you hover over ANSIBLE_ACTIONS_WARNING that it's a link.

**Comment by felixfontein** [comment]
#76 fixes this.
