### ISSUE TITLE
table overlaps text

### ISSUE THREAD

**Issue by samccann** [ansible-community/sphinx_ansible_theme#84]
### Summary

table overlaps text on  some pages. See Contributing to Ansible-maintained Collections page,  screenshot below.

![Screenshot 2023-02-03 at 3 08 33 PM](https://user-images.githubusercontent.com/1307746/216701328-fa8bf141-c81f-4cb6-a9b5-305a6d1d3926.png)

**Comment by samccann** [comment]
@felixfontein mentioned the cause as:

it's the `section [id]` hack, which apparently doesn't work when a list is followed by a table...
that hack is there because of the way the header works, to avoid that if you link to an anchor directly it's hidden by the header

**Comment by felixfontein** [comment]
It probably needs another 'exception' / special rule like https://github.com/ansible-community/sphinx_ansible_theme/blob/main/src/sphinx_ansible_theme/static/css/ansible.css#L476-L479

**Comment by felixfontein** [comment]
Link to HTML page where this happens: https://docs.ansible.com/ansible/devel/community/contributing_maintained_collections.html#ansible-maintained-collections

Simply changing line 476 to `section a[id], section table[id] {` should be fine. (It won't help when linking directly to a table, but that's already broken right now.)

**Comment by felixfontein** [comment]
#85 fixes this.
